# Generated by Django 4.2.5 on 2024-02-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='musicians',
        ),
    ]
