# Generated by Django 4.2.5 on 2024-02-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('skill_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Pro', 'Pro'), ('Maestro', 'Maestro')], max_length=20)),
                ('genre', models.CharField(choices=[('Soul', 'Soul'), ('Jazz', 'Jazz'), ('Benga', 'Benga'), ('Pop', 'Pop'), ('R&B', 'R&B'), ('Bongo', 'Bongo'), ('Chakacha', 'Chakacha'), ('Mugithi', 'Mugithi'), ('Traditional songs', 'Traditional songs')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
