# Generated by Django 4.2.5 on 2024-02-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_musicians_delete_musician'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musicians',
            new_name='Musician',
        ),
    ]
