# Generated by Django 4.2.5 on 2024-02-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_musicians_musician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='name',
        ),
        migrations.AddField(
            model_name='musician',
            name='fname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musician',
            name='lname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musician',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
