# Generated by Django 4.2.5 on 2024-02-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_musician_name_musician_fname_musician_lname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='charge_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musician',
            name='charge_rate_type',
            field=models.CharField(choices=[('hourly', 'Per Hour'), ('session', 'Per Session')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
