# Generated by Django 5.0.1 on 2024-02-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_musician_charge_rate_musician_charge_rate_type'),
    ]

    operations = [
            migrations.AlterField(
            model_name='musician',
            name='charge_rate_type',
            field=models.CharField(choices=[('hour', 'Per Hour'), ('session', 'Per Session')], max_length=10),
        ),
    ]
