# Generated by Django 5.0.1 on 2024-02-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_gig_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
