# Generated by Django 5.0.1 on 2024-02-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_gig_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='Profession_category',
            field=models.CharField(choices=[('', 'Select one'), ('singer', 'Singer'), ('songwriter', 'Songwriter'), ('producer', 'Producer'), ('vocalist', 'Vocalist'), ('band', 'Band'), ('instrumentalist', 'Instrumentalist'), ('sound-engineer', 'Sound Engineer'), ('music-educator', 'Music Educator'), ('folk-traditional', 'Folk and Traditional'), ('dj', 'DJ'), ('cover-band', 'Cover Band')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='dry_run',
            field=models.CharField(choices=[('', 'Select one'), ('Yes', 'Yes (Paid Separate)'), ('No', 'Yes (No payment)'), ('Full-after-job', 'NO'), ('Negotiable', 'To Be Determined')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='h_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='l_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='payment_policy',
            field=models.CharField(choices=[('', 'Select one'), ('Full-before-job', '100%: Before Job'), ('Half-before-after', '50%: Before and After'), ('Full-after-job', '100%: After Job'), ('Negotiable', 'Negotiable')], max_length=20, null=True),
        ),
    ]
