# Generated by Django 5.0.1 on 2024-02-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_client_user_alter_musician_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='client',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='date',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='username',
        ),
    ]
