# Generated by Django 5.0.1 on 2024-02-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_client_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='email',
        ),
        migrations.AlterField(
            model_name='client',
            name='preferred_genres',
            field=models.CharField(choices=[('Soul', 'Soul'), ('Jazz', 'Jazz'), ('Benga', 'Benga'), ('Pop', 'Pop'), ('R&B', 'R&B'), ('Bongo', 'Bongo'), ('Chakacha', 'Chakacha'), ('Mugithi', 'Mugithi'), ('Traditional songs', 'Traditional songs')], max_length=255),
        ),
    ]
