# Generated by Django 5.0.1 on 2024-02-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_client_email_remove_musician_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='dob',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('Individual', 'Individual')], max_length=20),
        ),
    ]
