# Generated by Django 5.0.1 on 2024-02-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_musician_dob_alter_client_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='charge_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
