# Generated by Django 5.0.1 on 2024-02-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_musician_charge_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='charge_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
