# Generated by Django 5.0.1 on 2024-02-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_musician_charge_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='musician',
            name='genre',
        ),
        migrations.AddField(
            model_name='musician',
            name='genres',
            field=models.ManyToManyField(choices=[('Soul', 'Soul'), ('Jazz', 'Jazz'), ('Benga', 'Benga'), ('Pop', 'Pop'), ('Rap', 'Rap'), ('R&B', 'R&B'), ('Bongo', 'Bongo'), ('Chakacha', 'Chakacha'), ('Mugithi', 'Mugithi'), ('Afro', 'Afro'), ('Alternative', 'Alternative'), ('Gospel', 'Gospel'), ('Country', 'Country'), ('Classical', 'Classical'), ('Blues', 'Blues'), ('Kigocho', 'Kigocho'), ('Reggae', 'Reggae'), ('Roots', 'Roots'), ('EDM', 'EDM'), ('K-Pop', 'K-Pop'), ('Funk', 'Funk'), ('Gengeton', 'Gengeton'), ('Poetry', 'Poetry'), ('House', 'House'), ('Choral', 'Choral')], max_length=20, to='core.genre'),
        ),
    ]
