# Generated by Django 5.0.1 on 2024-02-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_application_message_notification_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
