# Generated by Django 5.0.1 on 2024-02-26 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_musician_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='gig',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.gig'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.client'),
        ),
        migrations.AlterField(
            model_name='application',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.musician'),
        ),
    ]
