# Generated by Django 5.0.1 on 2024-02-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_gig_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='preferred_genres',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='preferred_genres',
            field=models.ManyToManyField(related_name='clients', to='core.genre'),
        ),
    ]
