# Generated by Django 5.0.1 on 2024-02-27 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_client_preferred_genres_alter_genre_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='genre',
        ),
        migrations.AddField(
            model_name='gig',
            name='genres',
            field=models.ManyToManyField(related_name='gigs', to='core.genre'),
        ),
        migrations.AlterField(
            model_name='application',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.client'),
        ),
        migrations.AlterField(
            model_name='application',
            name='musician',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.musician'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='core.client'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='genres',
            field=models.ManyToManyField(related_name='musicians', to='core.genre'),
        ),
        migrations.AlterField(
            model_name='review',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
