# Generated by Django 5.0.1 on 2024-02-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_musician_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='preferred_genres',
            new_name='genres',
        ),
    ]
