# Generated by Django 5.0.1 on 2024-03-03 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rename_preferred_genres_client_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.client'),
        ),
        migrations.AlterField(
            model_name='application',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.musician'),
        ),
    ]
