# Generated by Django 5.0.1 on 2024-03-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_client_profile_picture_musician_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
