# Generated by Django 5.0.1 on 2024-03-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_musician_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
