# Generated by Django 5.0.1 on 2024-03-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_musician_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
