# Generated by Django 5.0.1 on 2024-03-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_gig_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='h_budget',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='l_budget',
        ),
    ]
