# Generated by Django 5.0.1 on 2024-03-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_gig_deadline_remove_gig_h_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='event_date',
            field=models.DateField(null=True),
        ),
    ]
