# Generated by Django 5.0.1 on 2024-03-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_application_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('gig', 'musician')},
        ),
    ]
