# Generated by Django 5.0.1 on 2024-03-07 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_application_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gig'),
        ),
    ]
