# Generated by Django 5.0.1 on 2024-03-12 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_successfulhire'),
    ]

    operations = [
        migrations.AddField(
            model_name='successfulhire',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
