# Generated by Django 5.0.1 on 2024-03-14 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_application_status_alter_gig_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SuccessfulHire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.successfulhire')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.DeleteModel(
            name='MpesaPayment',
        ),
    ]
