# Generated by Django 5.0.1 on 2024-03-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_client_dob_alter_musician_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.AddField(
            model_name='musician',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='musician',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='musician',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
