# Generated by Django 5.0.1 on 2024-03-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_notification_recipient_musician_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pictures'),
        ),
    ]
