# Generated by Django 5.0.1 on 2024-03-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_musician_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images/profile_pictures'),
        ),
    ]
