# Generated by Django 5.0.1 on 2024-03-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_musician_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
