# Generated by Django 5.0.1 on 2024-03-19 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_client_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
