# Generated by Django 5.0.1 on 2024-03-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_gig_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='gig',
        ),
    ]
