# Generated by Django 5.0.1 on 2024-03-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_remove_gig_expiry_date_remove_review_gig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='successfulhire',
            name='completion_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Ongoing', max_length=20),
        ),
    ]
