# Generated by Django 5.0.1 on 2024-03-20 23:41

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_paid',
            field=models.DateTimeField(auto_now_add=True, default=datetime(2024, 2, 2)),
            preserve_default=False,

        ),
    ]
