# Generated by Django 5.0.1 on 2024-03-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_payment_date_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date_paid',
        ),
    ]
