# Generated by Django 5.0.1 on 2024-03-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_payment_date_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='musician',
            new_name='reviewee',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='client',
            new_name='reviewer',
        ),
    ]
