# Generated by Django 5.0.1 on 2024-03-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_rename_musician_review_reviewee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='SuccessfulHire',
            new_name='successfulhire',
        ),
    ]
