# Generated by Django 5.0.1 on 2024-03-22 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_payment_date_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='successfulhire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.successfulhire'),
        ),
    ]
