# Generated by Django 5.0.1 on 2024-03-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_payment_successfulhire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='genres',
            field=models.ManyToManyField(related_name='gigs', to='core.genre'),
        ),
    ]
