# Generated by Django 5.0.1 on 2024-03-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_gig_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='payment_policy',
        ),
        migrations.AddField(
            model_name='gig',
            name='event_policy',
            field=models.CharField(choices=[('', 'Select one'), ('Instruments-provided', '100%: Instruments-provided'), ('Come with yours', '50%: Come with yours')], max_length=20, null=True),
        ),
    ]
