# Generated by Django 5.0.1 on 2024-03-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_remove_gig_payment_policy_gig_event_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
