# Generated by Django 5.0.1 on 2024-03-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_client_facebook_client_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
