# Generated by Django 5.0.1 on 2024-03-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_client_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='sample1',
            field=models.FileField(blank=True, null=True, upload_to='sample_videos/'),
        ),
        migrations.AddField(
            model_name='musician',
            name='sample2',
            field=models.FileField(blank=True, null=True, upload_to='sample_videos/'),
        ),
    ]
