# Generated by Django 5.0.1 on 2024-03-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_musician_sample1_musician_sample2'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='profession_categories',
            field=models.CharField(blank=True, choices=[('Singer', 'Singer'), ('Songwriter', 'Songwriter'), ('Producer', 'Producer'), ('Vocalist', 'Vocalist'), ('Band', 'Band'), ('Instrumentalist', 'Instrumentalist'), ('Sound Engineer', 'Sound Engineer'), ('Music Educator', 'Music Educator'), ('Folk and Traditional', 'Folk and Traditional'), ('DJ', 'DJ'), ('Cover Band', 'Cover Band')], help_text='Select up to 4 profession categories for the musician.', max_length=50, null=True),
        ),
    ]
