# Generated by Django 5.0.1 on 2024-03-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_musician_profession_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='profession_categories',
        ),
        migrations.AddField(
            model_name='musician',
            name='profession_category',
            field=models.CharField(blank=True, choices=[('singer', 'Singer'), ('songwriter', 'Songwriter'), ('producer', 'Producer'), ('vocalist', 'Vocalist'), ('band', 'Band'), ('instrumentalist', 'Instrumentalist'), ('sound-engineer', 'Sound Engineer'), ('music-educator', 'Music Educator'), ('folk-traditional', 'Folk and Traditional'), ('dj', 'DJ'), ('cover-band', 'Cover Band')], max_length=25),
        ),
    ]
