# Generated by Django 5.0.1 on 2024-03-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_remove_musician_profession_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='event_type',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('corporate', 'Corporate Event'), ('festival', 'Festival'), ('graduation', 'Graduation'), ('wedding', 'Wedding'), ('concert', 'Concert'), ('private_party', 'Private Party'), ('club_event', 'Club Event'), ('bar_mitzvah', 'Bar Mitzvah'), ('bat_mitzvah', 'Bat Mitzvah'), ('anniversary', 'Anniversary'), ('charity_event', 'Charity Event'), ('holiday_party', 'Holiday Party'), ('awards_ceremony', 'Awards Ceremony'), ('reception', 'Reception'), ('school_event', 'School Event'), ('fundraiser', 'Fundraiser'), ('fair', 'Fair'), ('conference', 'Conference'), ('community_event', 'Community Event'), ('religious_event', 'Religious Event'), ('cruise_ship_event', 'Cruise Ship Event'), ('sporting_event', 'Sporting Event'), ('art_gallery_opening', 'Art Gallery Opening'), ('film_premiere', 'Film Premiere'), ('book_launch', 'Book Launch'), ('trade_show', 'Trade Show'), ('political_rally', 'Political Rally'), ('protest', 'Protest')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='event_policy',
            field=models.CharField(choices=[('', 'Select one'), ('Instruments-provided', '100%: Instruments-provided'), ('Come with yours', '50%: Come with yours'), ('Negotiable', 'Negotiable')], max_length=20, null=True),
        ),
    ]
