# Generated by Django 5.0.1 on 2024-03-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_gig_event_type_alter_gig_event_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='email',
        ),
        migrations.AlterField(
            model_name='gig',
            name='Profession_category',
            field=models.CharField(choices=[('', 'Select one'), ('Singer', 'Singer'), ('Songwriter', 'Songwriter'), ('Producer', 'Producer'), ('Vocalist', 'Vocalist'), ('Band', 'Band'), ('Instrumentalist', 'Instrumentalist'), ('Sound-engineer', 'Sound Engineer'), ('Music-educator', 'Music Educator'), ('Folk-traditional', 'Folk and Traditional'), ('Dj', 'DJ'), ('Cover-band', 'Cover Band')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='event_type',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Corporate Event', 'Corporate Event'), ('Festival', 'Festival'), ('Graduation', 'Graduation'), ('Wedding', 'Wedding'), ('Concert', 'Concert'), ('Private Party', 'Private Party'), ('Club Event', 'Club Event'), ('Bar Mitzvah', 'Bar Mitzvah'), ('Bat Mitzvah', 'Bat Mitzvah'), ('Anniversary', 'Anniversary'), ('Charity Event', 'Charity Event'), ('Holiday Party', 'Holiday Party'), ('Awards Ceremony', 'Awards Ceremony'), ('Reception', 'Reception'), ('School Event', 'School Event'), ('Fundraiser', 'Fundraiser'), ('Fair', 'Fair'), ('Conference', 'Conference'), ('Community Event', 'Community Event'), ('Religious Event', 'Religious Event'), ('Cruise Ship Event', 'Cruise Ship Event'), ('Sporting Event', 'Sporting Event'), ('Art Gallery Opening', 'Art Gallery Opening'), ('Film Premiere', 'Film Premiere'), ('Book Launch', 'Book Launch'), ('Trade Show', 'Trade Show'), ('Political Rally', 'Political Rally'), ('Protest', 'Protest')], max_length=20, null=True),
        ),
    ]
