# Generated by Django 5.0.1 on 2024-03-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_remove_gig_email_alter_gig_profession_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
    ]
